#!/usr/bin/env node
/**
 * OpenClaw Hatch — interactive one-shot setup
 * Run: npm run setup (or node setup.js)
 *
 * 1. Reads existing .env if present
 * 2. Prompts for missing config (PRIVILEGED_CALLER_ID, API keys)
 * 3. Writes .env
 * 4. Boots the server
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const ENV_PATH = path.join(__dirname, '.env');

const C = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  white: '\x1b[37m',
};

function parseEnvFile(filePath) {
  const env = {};
  if (!fs.existsSync(filePath)) return env;
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    let val = trimmed.slice(eqIndex + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  }
  return env;
}

function writeEnvFile(filePath, env) {
  const lines = ['# OpenClaw .env — generated by npm run setup', ''];
  const sections = {
    'Privilege': ['PRIVILEGED_CALLER_ID'],
    'Cloud LLM Providers': ['MINIMAX_API_KEY', 'GROQ_API_KEY', 'ANTHROPIC_API_KEY', 'OPENAI_API_KEY'],
    'External Brain': ['NYAN_API_TOKEN'],
    'Security': ['SESSION_SECRET'],
    'Local': ['OLLAMA_URL', 'OPENCLAW_WORKSPACE'],
  };

  for (const [section, keys] of Object.entries(sections)) {
    const sectionLines = [];
    for (const key of keys) {
      if (env[key]) sectionLines.push(`${key}=${env[key]}`);
    }
    if (sectionLines.length > 0) {
      lines.push(`# ${section}`);
      lines.push(...sectionLines);
      lines.push('');
    }
  }

  fs.writeFileSync(filePath, lines.join('\n'));
}

function ask(rl, question) {
  return new Promise(resolve => rl.question(question, resolve));
}

function status(key, val) {
  if (val) return `${C.green}[set]${C.reset} ${C.dim}${key}${C.reset}`;
  return `${C.yellow}[---]${C.reset} ${C.dim}${key}${C.reset}`;
}

async function main() {
  console.log('');
  console.log(`${C.bold}${C.cyan}  ╔══════════════════════════════╗${C.reset}`);
  console.log(`${C.bold}${C.cyan}  ║   ${C.white}OPENCLAW HATCH${C.cyan}   ${C.dim}setup${C.cyan}     ║${C.reset}`);
  console.log(`${C.bold}${C.cyan}  ╚══════════════════════════════╝${C.reset}`);
  console.log('');

  const existing = parseEnvFile(ENV_PATH);
  const merged = { ...existing };

  for (const [k, v] of Object.entries(process.env)) {
    if (['PRIVILEGED_CALLER_ID', 'MINIMAX_API_KEY', 'GROQ_API_KEY', 'ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'NYAN_API_TOKEN', 'SESSION_SECRET', 'OLLAMA_URL', 'OPENCLAW_WORKSPACE'].includes(k) && v) {
      if (!merged[k]) merged[k] = v;
    }
  }

  console.log(`${C.bold}  Current config:${C.reset}`);
  console.log(`  ${status('PRIVILEGED_CALLER_ID', merged.PRIVILEGED_CALLER_ID)}`);
  console.log(`  ${status('NYAN_API_TOKEN', merged.NYAN_API_TOKEN)}`);
  console.log(`  ${status('MINIMAX_API_KEY', merged.MINIMAX_API_KEY)}`);
  console.log(`  ${status('GROQ_API_KEY', merged.GROQ_API_KEY)}`);
  console.log(`  ${status('ANTHROPIC_API_KEY', merged.ANTHROPIC_API_KEY)}`);
  console.log(`  ${status('OPENAI_API_KEY', merged.OPENAI_API_KEY)}`);
  console.log(`  ${status('SESSION_SECRET', merged.SESSION_SECRET)}`);
  console.log('');

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  if (!merged.PRIVILEGED_CALLER_ID) {
    const id = await ask(rl, `${C.cyan}  Privileged caller ID${C.reset} ${C.dim}(phone/email/username, Enter to skip):${C.reset} `);
    if (id.trim()) merged.PRIVILEGED_CALLER_ID = id.trim();
  } else {
    const raw = merged.PRIVILEGED_CALLER_ID;
    const masked = raw.length > 6 ? raw.slice(0, 3) + '***' + raw.slice(-3) : '***';
    console.log(`  ${C.green}Privilege:${C.reset} ${masked} ${C.dim}(already set)${C.reset}`);
  }

  if (!merged.NYAN_API_TOKEN) {
    const token = await ask(rl, `${C.cyan}  Nyan API token${C.reset} ${C.dim}(Enter to skip):${C.reset} `);
    if (token.trim()) merged.NYAN_API_TOKEN = token.trim();
  }

  const cloudKeys = [
    { key: 'MINIMAX_API_KEY', label: 'MiniMax API key' },
    { key: 'GROQ_API_KEY', label: 'Groq API key' },
    { key: 'ANTHROPIC_API_KEY', label: 'Anthropic/Claude API key' },
    { key: 'OPENAI_API_KEY', label: 'OpenAI API key' },
  ];

  const hasAnyCloud = cloudKeys.some(c => merged[c.key]);
  if (!hasAnyCloud) {
    console.log('');
    console.log(`  ${C.yellow}No cloud LLM keys set.${C.reset} ${C.dim}At least one recommended (or use Ollama locally).${C.reset}`);
    for (const c of cloudKeys) {
      const val = await ask(rl, `  ${C.cyan}${c.label}${C.reset} ${C.dim}(Enter to skip):${C.reset} `);
      if (val.trim()) {
        merged[c.key] = val.trim();
        break;
      }
    }
  }

  rl.close();

  writeEnvFile(ENV_PATH, merged);
  console.log('');
  console.log(`  ${C.green}.env written${C.reset} ${C.dim}(${ENV_PATH})${C.reset}`);
  console.log('');

  console.log(`${C.bold}  Hatching...${C.reset}`);
  console.log('');

  const server = spawn('node', ['index.js'], {
    cwd: __dirname,
    stdio: 'inherit',
    env: { ...process.env, ...merged }
  });

  server.on('close', (code) => process.exit(code || 0));

  process.on('SIGINT', () => { server.kill('SIGINT'); });
  process.on('SIGTERM', () => { server.kill('SIGTERM'); });
}

main().catch(e => {
  console.error(`${C.red}Setup failed:${C.reset}`, e.message);
  process.exit(1);
});
